### ISSUE TITLE
App name

### ISSUE THREAD

**Issue by jonatsh** [isel-leic-ls/1718-1-common#4]
O nome da aplicação não seria isel-ls-1718-**1**-g<número-do-grupo> em vez de isel-ls-1718-**2**-g<número-do-grupo> como está escrito na página da fase 4? 

E também na parte onde diz heroku git:remote -a isel-ls-1718-2-gXX

@pmhsfelix

**Comment by pmhsfelix** [comment]
Sim, deve ser `isel-ls-1718-1-g<número-do-grupo>`. Obrigado pela correcção.
